version: '3'

services:
  web:
    build:
      context: .
      args:
        GITHUB_USER: "milhodroid"
        GITHUB_EMAIL: "luizcarlosdev@gmail.com"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
