# Generated by Django 5.1.8 on 2025-04-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorados',
            name='estagio',
            field=models.CharField(choices=[('E1', '10-100'), ('E2', '100-500'), ('E3', '500-1000')], max_length=2),
        ),
    ]
